name: Auto merge
on:
  pull_request:
permissions:
  contents: write
  checks: read
  pull-requests: write
jobs:
  auto-merge:
    uses: clouddrove/github-shared-workflows/.github/workflows/auto_merge.yml@7d78c7b4b3922e7577e222d4f48f1197c7d507c8 # pinned to latest
    with:
      azure_cloud: true
      tfchecks_azure: '["tf-lint / tflint"]'
    secrets:
      GITHUB: ${{ secrets.GITHUB }}
