name: PR Validation

on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize
      - reopened

jobs:
  pr-validation:
    if: github.actor != 'dependabot[bot]'
    uses: clouddrove/github-shared-workflows/.github/workflows/pr-checks.yml@a9fc2fae0eceafcdd4a812c23a3febd9c416428b # pinned to latest
    secrets: inherit
    with:
      subjectPattern: '^.+$'
